//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReflectWILinks {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ProcessParameters : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProcessParameters defaultInstance = ((ProcessParameters)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProcessParameters())));
        
        public static ProcessParameters Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddMissingChangesets {
            get {
                return ((bool)(this["AddMissingChangesets"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddMissingRelated {
            get {
                return ((bool)(this["AddMissingRelated"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddMissingOtherExternal {
            get {
                return ((bool)(this["AddMissingOtherExternal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://my-tfs:8080/tfs")]
        public global::System.Uri TargetTfsUri {
            get {
                return ((global::System.Uri)(this["TargetTfsUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://myother-tfs:8080/tfs")]
        public global::System.Uri SourceTfsUri {
            get {
                return ((global::System.Uri)(this["SourceTfsUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3e983292-3715-4c5e-8c37-43d6baf8ce36")]
        public global::System.Guid ScopeQueryGuid {
            get {
                return ((global::System.Guid)(this["ScopeQueryGuid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("164d7513-e460-4429-8709-dfce48047590")]
        public global::System.Guid TargetQueryGuid {
            get {
                return ((global::System.Guid)(this["TargetQueryGuid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADVC7")]
        public string TargetProject {
            get {
                return ((string)(this["TargetProject"]));
            }
        }
    }
}
